# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/stockOCR.py"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/stockOCR.py"
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
            
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ducatsOCR/requirements.txt
    - name: Build with PyInstaller
      run: |
        pyinstaller ducatsOCR/stockOCR.spec

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nutCracker
        path: dist/
